build:
	docker build --rm -t $(PROJECT_NAME):$(RELEASE_NUMBER)_dev_$(TIMESTAMPS) .
push_qa:
	docker tag $(PROJECT_NAME):$(RELEASE_NUMBER)_dev_$(TIMESTAMPS) $(DOCKER_REGISTRY)/$(PROJECT_NAME):$(RELEASE_NUMBER)_qa_$(TIMESTAMPS)
	docker push $(DOCKER_REGISTRY)/$(PROJECT_NAME):$(RELEASE_NUMBER)_qa_$(TIMESTAMPS)
push_prod:
	docker tag $(DOCKER_REGISTRY)/$(PROJECT_NAME):$(RELEASE_NUMBER)_qa_$(TIMESTAMPS) $(DOCKER_REGISTRY)/$(PROJECT_NAME):$(RELEASE_NUMBER)_prod_$(TIMESTAMPS)
	docker push $(DOCKER_REGISTRY)/$(PROJECT_NAME):$(RELEASE_NUMBER)_qa_$(TIMESTAMPS)
run:
	EDIT_HERE
test:
	EDIT_HERE
run_frontend:
	EDIT_HERE
clean:
	EDIT_HERE